### ISSUE TITLE
Expose various feedbacks as variables, and/or add actions to turn features on or off, not just toggle

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-roland-v60hd#11]
Would it be possible to expose the feedbacks that area already provided as variables from the module as well?  In particular, the status of the DSK and PIP system would be most helpful to me.

I'd like to be able to push a button that would turn my DSK on if it isn't already turned on, and ignore the button push if it were already turned on.   With the feedbacks exposed as variables, I can create my own custom processing with the push button based on variable button actions that already exist.  It would be cleaner to have all of that happen in the background with code, but I'll take what I can get...

Another use case for this would be for the input feedbacks.  I know there are various tally systems on the market already, but by exposing the feedback associated with each input as to when it is selected for PVW, PGM, or AUX, one could create their own tally system with cheap kasa smart bulbs or plugs even through the use of triggers for just about any scenario imaginable...

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-roland-v60hd/commit/dc5980d136ba2318291395cfcafcaf99fd60705c

Added the latest version of this module to the betas for you, it supports two new actions, dsk_on and dsk_off, which use the same logic from feedbacks and if DSK is on and you press dsk_on, it won't do anything, etc.
