### ISSUE TITLE
PROBLEM WITH ROLAND V60 HD

### ISSUE THREAD

**Issue by pito456** [bitfocus/companion-module-roland-v60hd#2]
HELLO THE PROBLEM THAT I HAVE ONCE CONFIGURED THE STREAM DECK THE KEY ASSIGNMENT WORKS PERFECTLY BUT DOES NOT LET ME USE THE TABLE SOFTWARE SIMULTANEOUSLY FOR EXAMPLE WITH BLACKMAGIC ATEM IF IT WORKS SIMULTANEOUSLY A BUG? OR DO I HAVE ANY CONFIGURATION PROBLEM?

THANK YOU AND FORGIVENESS FOR MY ENGLISH

**Comment by josephdadams** [comment]
Table software?

**Comment by willosof** [comment]
Sorry @pito456, could you please turn off caps lock and try to explain the steps of your problem more precisely? Would it help to use google translate in your own language and translate it into English?

**Comment by pito456** [comment]
Hello sorry for English and capital letters.
The problem is the following:
when I am using the stream deck with the roland v60 hd console,
communication with the 60HD Remote Control Software is disconnected.
I cannot work simultaneously with the stream deck and the 60HD Remote
Control Software.
I hope this serves you
thank you very much and forgive for the inconvenience
Greetings

**Comment by JeffreyDavidsz** [comment]
Can you try to connect a different PC/MAC with the remote control software? Some hardware/software will allow only 1 connection

**Comment by pito456** [comment]
Hello
if that is the problem just leave 1 device simultaneously
thank you very much to all.
  let's see if roland changes this that would be a major improvement

**Comment by JeffreyDavidsz** [comment]
Well I don't know but it would be good to share, could you test that please?

**Comment by pito456** [comment]
If I've tried it and it s actually only working on 1 device

Enviado desde mi iPhone

**Comment by JeffreyDavidsz** [comment]
Thanks, then I will close this issue
