### ISSUE TITLE
Add instance feedback for Roland V-60HD

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-roland-v60hd#3]
I would find it very helpful to have an instance feedback option to change the colors for buttons based on the input source, and for the preview source.  For example, we have several PTZ Optics cameras we will use with our V-60HD.  It would be nice to be able to have all stream deck buttons associated with the camera that is currently live switch to a red background, and have all buttons associated with the camera that is currently in preview switch to a green background, and all other buttons for cameras not in preview or live be set to the button default colors as defined in setup.    In this way we could prevent our less technical operators from accidentally making camera movements on live cameras due to real-time feedback.

Thanks for your time!

**Comment by jrviz** [comment]
PR created. I have not done a version bump on the package
