### ISSUE TITLE
Additional Feedback Request

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-roland-v60hd#7]
Currently there are only 3 feedbacks provided for the v-60HD.  As we've been using this device more and more, I've found there would be significant utility in building out the remaining feedbacks on this device.  

The three existing feedbacks are:
Program Status
Preview Status
Aux Status

Specifically requested to be added include:
PinP1 selected
PinP2 selected
SPLIT selected
MIX selected
WIPE 1 selected
WIPE 2 selected
DSK PVW selected
Mode selected (green: aux, blue: memory)
Output fade selected
HDCP status
DSK selected

I'm very willing to participate in testing if anyone has the skill to program these but lacks the hardware to test.

Thanks in advance!

**Comment by josephdadams** [comment]
@jrviz something you can help with?

**Comment by jrviz** [comment]
Yes, I can. I put those initial feedbacks in as they seemed the most useful but I'll take a look at the others.

Jon, I'll let you know when there is something to test. I still have your email address (assuming it has remained the same).

**Comment by jsnyder886** [comment]
James!  You rock man.  Yep, still the same.  Thanks so much!

**Comment by jrviz** [comment]
@josephdadams PR ready to merge, version updated in package.json

**Comment by josephdadams** [comment]
This is in the latest beta builds now
